/**
 * Copyright (c) 2020-present, Wuba, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wpai.proto

package com.bj58.ailab.dlpredictonline.grpc;

/**
 * grpc自动生成文件
 * @author 58
 */
public final class WpaiDLPredictOnline {
    private WpaiDLPredictOnline() {}
    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictResponse_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_bj58_ailab_wpai_grpc_PredictRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_bj58_ailab_wpai_grpc_PredictRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
        internal_static_com_bj58_ailab_wpai_grpc_PredictResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internal_static_com_bj58_ailab_wpai_grpc_PredictResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
        descriptor;
    static {
        String[] descriptorData = {
            "\n\nwpai.proto\022\030com.bj58.ailab.wpai.grpc\"\'" +
                "\n\025PytorchPredictRequest\022\016\n\006inputs\030\001 \001(\t\"" +
                ")\n\026PytorchPredictResponse\022\017\n\007outputs\030\001 \001" +
                "(\t\" \n\016PredictRequest\022\016\n\006inputs\030\001 \001(\t\"\"\n\017" +
                "PredictResponse\022\017\n\007outputs\030\001 \001(\t2\361\001\n\032Wpa" +
                "iDLPredictOnlineService\022^\n\007Predict\022(.com" +
                ".bj58.ailab.wpai.grpc.PredictRequest\032).c" +
                "om.bj58.ailab.wpai.grpc.PredictResponse\022" +
                "s\n\016PytorchPredict\022/.com.bj58.ailab.wpai." +
                "grpc.PytorchPredictRequest\0320.com.bj58.ai" +
                "lab.wpai.grpc.PytorchPredictResponseB1\n\030" +
                "com.bj58.ailab.wpai.grpcB\023WpaiDLPredictO" +
                "nlineP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                @Override
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                }, assigner);
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictRequest_descriptor,
            new String[] { "Inputs", });
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
        internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bj58_ailab_wpai_grpc_PytorchPredictResponse_descriptor,
            new String[] { "Outputs", });
        internal_static_com_bj58_ailab_wpai_grpc_PredictRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
        internal_static_com_bj58_ailab_wpai_grpc_PredictRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bj58_ailab_wpai_grpc_PredictRequest_descriptor,
            new String[] { "Inputs", });
        internal_static_com_bj58_ailab_wpai_grpc_PredictResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
        internal_static_com_bj58_ailab_wpai_grpc_PredictResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_bj58_ailab_wpai_grpc_PredictResponse_descriptor,
            new String[] { "Outputs", });
    }

  // @@protoc_insertion_point(outer_class_scope)
}
