/**
 * Copyright (c) 2020-present, Wuba, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wpai.proto
package com.bj58.ailab.dlpredictonline.grpc;

/**
 * grpc编译自动生成文件
 * @author 58
 */
public final class WpaiDLPredictOnline {
  private WpaiDLPredictOnline() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nwpai.proto\022#com.bj58.ailab.dlpredicton" +
      "line.grpc\"\'\n\025PytorchPredictRequest\022\016\n\006in" +
      "puts\030\001 \001(\t\")\n\026PytorchPredictResponse\022\017\n\007" +
      "outputs\030\001 \001(\t\" \n\016PredictRequest\022\016\n\006input" +
      "s\030\001 \001(\t\"\"\n\017PredictResponse\022\017\n\007outputs\030\001 " +
      "\001(\t\"%\n\023CaffePredictRequest\022\016\n\006inputs\030\001 \001" +
      "(\t\"\'\n\024CaffePredictResponse\022\017\n\007outputs\030\001 " +
      "\001(\t\"#\n\021TisPredictRequest\022\016\n\006inputs\030\001 \001(\t" +
      "\"%\n\022TisPredictResponse\022\017\n\007outputs\030\001 \001(\t2" +
      "\253\004\n\032WpaiDLPredictOnlineService\022v\n\007Predic",
      "t\0223.com.bj58.ailab.dlpredictonline.grpc." +
      "PredictRequest\0324.com.bj58.ailab.dlpredic" +
      "tonline.grpc.PredictResponse\"\000\022\213\001\n\016Pytor" +
      "chPredict\022:.com.bj58.ailab.dlpredictonli" +
      "ne.grpc.PytorchPredictRequest\032;.com.bj58" +
      ".ailab.dlpredictonline.grpc.PytorchPredi" +
      "ctResponse\"\000\022\205\001\n\014CaffePredict\0228.com.bj58" +
      ".ailab.dlpredictonline.grpc.CaffePredict" +
      "Request\0329.com.bj58.ailab.dlpredictonline" +
      ".grpc.CaffePredictResponse\"\000\022\177\n\nTisPredi",
      "ct\0226.com.bj58.ailab.dlpredictonline.grpc" +
      ".TisPredictRequest\0327.com.bj58.ailab.dlpr" +
      "edictonline.grpc.TisPredictResponse\"\000B<\n" +
      "#com.bj58.ailab.dlpredictonline.grpcB\023Wp" +
      "aiDLPredictOnlineP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictRequest_descriptor,
        new String[] { "Inputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_PytorchPredictResponse_descriptor,
        new String[] { "Outputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictRequest_descriptor,
        new String[] { "Inputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_PredictResponse_descriptor,
        new String[] { "Outputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictRequest_descriptor,
        new String[] { "Inputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_CaffePredictResponse_descriptor,
        new String[] { "Outputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictRequest_descriptor,
        new String[] { "Inputs", });
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bj58_ailab_dlpredictonline_grpc_TisPredictResponse_descriptor,
        new String[] { "Outputs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
